### ISSUE TITLE
discretize_vector method="natural" crashes R when applied to non-numeric column

### ISSUE THREAD

**Issue by Quirouette** [stscl/sdsfun#12] opened 2024-10-09 17:44 UTC
Thank you kindly for your contribution!

Something I noticed:

library(sdsfun)
sapply(iris, discretize_vector, n=5, method="sd")
sd (Success), equal (Success), quantile (Success), geometric (Success), natural (Crash)

sapply(iris[,1:4], discretize_vector, n=5, method="natural")
Success
discretize_vector(iris[,5], n=5, method="natural")
Crash

Thanks again!
Justin

##################################################### 
Session info:
R version 4.4.1 (2024-06-14 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.utf8  LC_CTYPE=English_Canada.utf8   
[3] LC_MONETARY=English_Canada.utf8 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sdsfun_0.4.0

loaded via a namespace (and not attached):
[1] compiler_4.4.1 magrittr_2.0.3 Rcpp_1.0.13

**Comment by SpatLyu** [comment] 2024-10-10 02:09
Thank you for your report. The crash caused by the natural breaks function in R was due to the 5th column of the input data, i.e., `iris[,5]`, being of factor type. The `discretize_vector` function is implemented in C++ using Rcpp, and when I initially designed the function, I only accounted for numeric types like `double` and `integer`; I didn't consider character or factor inputs. I have now fixed this issue in the latest development version on GitHub. Currently, in `discretize_vector`, any input of `factor` or `character` type will first be converted to a `factor` and then to an `integer` before being returned. If you have any other suggestions, please let me know.

- install the latest development version on github:
```r
# install.packages("devtools")
devtools::install_github("stscl/sdsfun", dep = TRUE)
```
- test the `discretize_vector` function:
``` r
library(sdsfun)
sapply(iris, discretize_vector, n=5, method="natural")
#>        Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>   [1,]            1           4            1           1       1
#>   [2,]            1           3            1           1       1
#>   [3,]            1           4            1           1       1
#>   [4,]            1           3            1           1       1
#>   [5,]            1           5            1           1       1
#>   [6,]            2           5            1           1       1
#>   [7,]            1           4            1           1       1
#>   [8,]            1           4            1           1       1
#>   [9,]            1           3            1           1       1
#>  [10,]            1           3            1           1       1
#>  [11,]            2           5            1           1       1
#>  [12,]            1           4            1           1       1
#>  [13,]            1           3            1           1       1
#>  [14,]            1           3            1           1       1
#>  [15,]            2           5            1           1       1
#>  [16,]            2           5            1           1       1
#>  [17,]            2           5            1           1       1
#>  [18,]            1           4            1           1       1
#>  [19,]            2           5            1           1       1
#>  [20,]            1           5            1           1       1
#>  [21,]            2           4            1           1       1
#>  [22,]            1           5            1           1       1
#>  [23,]            1           5            1           1       1
#>  [24,]            1           4            1           1       1
#>  [25,]            1           4            2           1       1
#>  [26,]            1           3            1           1       1
#>  [27,]            1           4            1           1       1
#>  [28,]            2           4            1           1       1
#>  [29,]            2           4            1           1       1
#>  [30,]            1           4            1           1       1
#>  [31,]            1           3            1           1       1
#>  [32,]            2           4            1           1       1
#>  [33,]            2           5            1           1       1
#>  [34,]            2           5            1           1       1
#>  [35,]            1           3            1           1       1
#>  [36,]            1           4            1           1       1
#>  [37,]            2           4            1           1       1
#>  [38,]            1           5            1           1       1
#>  [39,]            1           3            1           1       1
#>  [40,]            1           4            1           1       1
#>  [41,]            1           4            1           1       1
#>  [42,]            1           1            1           1       1
#>  [43,]            1           4            1           1       1
#>  [44,]            1           4            1           2       1
#>  [45,]            1           5            2           1       1
#>  [46,]            1           3            1           1       1
#>  [47,]            1           5            1           1       1
#>  [48,]            1           4            1           1       1
#>  [49,]            2           5            1           1       1
#>  [50,]            1           4            1           1       1
#>  [51,]            5           4            3           3       2
#>  [52,]            4           4            3           3       2
#>  [53,]            4           3            4           3       2
#>  [54,]            2           1            2           3       2
#>  [55,]            4           2            3           3       2
#>  [56,]            2           2            3           3       2
#>  [57,]            3           4            3           4       2
#>  [58,]            1           1            2           2       2
#>  [59,]            4           3            3           3       2
#>  [60,]            2           2            2           3       2
#>  [61,]            1           1            2           2       2
#>  [62,]            3           3            3           3       2
#>  [63,]            3           1            2           2       2
#>  [64,]            3           3            3           3       2
#>  [65,]            2           3            2           3       2
#>  [66,]            4           3            3           3       2
#>  [67,]            2           3            3           3       2
#>  [68,]            2           2            2           2       2
#>  [69,]            3           1            3           3       2
#>  [70,]            2           2            2           2       2
#>  [71,]            3           4            3           4       2
#>  [72,]            3           2            2           3       2
#>  [73,]            3           2            4           3       2
#>  [74,]            3           2            3           3       2
#>  [75,]            4           3            3           3       2
#>  [76,]            4           3            3           3       2
#>  [77,]            4           2            3           3       2
#>  [78,]            4           3            4           4       2
#>  [79,]            3           3            3           3       2
#>  [80,]            2           2            2           2       2
#>  [81,]            2           1            2           2       2
#>  [82,]            2           1            2           2       2
#>  [83,]            2           2            2           3       2
#>  [84,]            3           2            4           4       2
#>  [85,]            2           3            3           3       2
#>  [86,]            3           4            3           4       2
#>  [87,]            4           3            3           3       2
#>  [88,]            3           1            3           3       2
#>  [89,]            2           3            2           3       2
#>  [90,]            2           2            2           3       2
#>  [91,]            2           2            3           3       2
#>  [92,]            3           3            3           3       2
#>  [93,]            2           2            2           3       2
#>  [94,]            1           1            2           2       2
#>  [95,]            2           2            3           3       2
#>  [96,]            2           3            3           3       2
#>  [97,]            2           3            3           3       2
#>  [98,]            3           3            3           3       2
#>  [99,]            1           2            2           2       2
#> [100,]            2           2            2           3       2
#> [101,]            3           4            5           5       3
#> [102,]            2           2            4           4       3
#> [103,]            5           3            5           5       3
#> [104,]            3           3            4           4       3
#> [105,]            4           3            5           5       3
#> [106,]            5           3            5           5       3
#> [107,]            1           2            3           4       3
#> [108,]            5           3            5           4       3
#> [109,]            4           2            5           4       3
#> [110,]            5           5            5           5       3
#> [111,]            4           4            4           5       3
#> [112,]            4           2            4           4       3
#> [113,]            4           3            4           5       3
#> [114,]            2           2            4           5       3
#> [115,]            2           2            4           5       3
#> [116,]            4           4            4           5       3
#> [117,]            4           3            4           4       3
#> [118,]            5           5            5           5       3
#> [119,]            5           2            5           5       3
#> [120,]            3           1            4           3       3
#> [121,]            4           4            5           5       3
#> [122,]            2           2            4           5       3
#> [123,]            5           2            5           5       3
#> [124,]            3           2            4           4       3
#> [125,]            4           4            5           5       3
#> [126,]            5           4            5           4       3
#> [127,]            3           2            3           4       3
#> [128,]            3           3            4           4       3
#> [129,]            4           2            4           5       3
#> [130,]            5           3            5           4       3
#> [131,]            5           2            5           4       3
#> [132,]            5           5            5           5       3
#> [133,]            4           2            4           5       3
#> [134,]            3           2            4           3       3
#> [135,]            3           2            4           3       3
#> [136,]            5           3            5           5       3
#> [137,]            3           4            4           5       3
#> [138,]            4           3            4           4       3
#> [139,]            3           3            3           4       3
#> [140,]            4           3            4           5       3
#> [141,]            4           3            4           5       3
#> [142,]            4           3            4           5       3
#> [143,]            2           2            4           4       3
#> [144,]            4           4            5           5       3
#> [145,]            4           4            5           5       3
#> [146,]            4           3            4           5       3
#> [147,]            3           2            4           4       3
#> [148,]            4           3            4           5       3
#> [149,]            3           4            4           5       3
#> [150,]            3           3            4           4       3
sapply(iris[,1:4], discretize_vector, n=5, method="natural")
#>        Sepal.Length Sepal.Width Petal.Length Petal.Width
#>   [1,]            1           4            1           1
#>   [2,]            1           3            1           1
#>   [3,]            1           4            1           1
#>   [4,]            1           3            1           1
#>   [5,]            1           5            1           1
#>   [6,]            2           5            1           1
#>   [7,]            1           4            1           1
#>   [8,]            1           4            1           1
#>   [9,]            1           3            1           1
#>  [10,]            1           3            1           1
#>  [11,]            2           5            1           1
#>  [12,]            1           4            1           1
#>  [13,]            1           3            1           1
#>  [14,]            1           3            1           1
#>  [15,]            2           5            1           1
#>  [16,]            2           5            1           1
#>  [17,]            2           5            1           1
#>  [18,]            1           4            1           1
#>  [19,]            2           5            1           1
#>  [20,]            1           5            1           1
#>  [21,]            2           4            1           1
#>  [22,]            1           5            1           1
#>  [23,]            1           5            1           1
#>  [24,]            1           4            1           1
#>  [25,]            1           4            2           1
#>  [26,]            1           3            1           1
#>  [27,]            1           4            1           1
#>  [28,]            2           4            1           1
#>  [29,]            2           4            1           1
#>  [30,]            1           4            1           1
#>  [31,]            1           3            1           1
#>  [32,]            2           4            1           1
#>  [33,]            2           5            1           1
#>  [34,]            2           5            1           1
#>  [35,]            1           3            1           1
#>  [36,]            1           4            1           1
#>  [37,]            2           4            1           1
#>  [38,]            1           5            1           1
#>  [39,]            1           3            1           1
#>  [40,]            1           4            1           1
#>  [41,]            1           4            1           1
#>  [42,]            1           1            1           1
#>  [43,]            1           4            1           1
#>  [44,]            1           4            1           2
#>  [45,]            1           5            2           1
#>  [46,]            1           3            1           1
#>  [47,]            1           5            1           1
#>  [48,]            1           4            1           1
#>  [49,]            2           5            1           1
#>  [50,]            1           4            1           1
#>  [51,]            5           4            3           3
#>  [52,]            4           4            3           3
#>  [53,]            4           3            4           3
#>  [54,]            2           1            2           3
#>  [55,]            4           2            3           3
#>  [56,]            2           2            3           3
#>  [57,]            3           4            3           4
#>  [58,]            1           1            2           2
#>  [59,]            4           3            3           3
#>  [60,]            2           2            2           3
#>  [61,]            1           1            2           2
#>  [62,]            3           3            3           3
#>  [63,]            3           1            2           2
#>  [64,]            3           3            3           3
#>  [65,]            2           3            2           3
#>  [66,]            4           3            3           3
#>  [67,]            2           3            3           3
#>  [68,]            2           2            2           2
#>  [69,]            3           1            3           3
#>  [70,]            2           2            2           2
#>  [71,]            3           4            3           4
#>  [72,]            3           2            2           3
#>  [73,]            3           2            4           3
#>  [74,]            3           2            3           3
#>  [75,]            4           3            3           3
#>  [76,]            4           3            3           3
#>  [77,]            4           2            3           3
#>  [78,]            4           3            4           4
#>  [79,]            3           3            3           3
#>  [80,]            2           2            2           2
#>  [81,]            2           1            2           2
#>  [82,]            2           1            2           2
#>  [83,]            2           2            2           3
#>  [84,]            3           2            4           4
#>  [85,]            2           3            3           3
#>  [86,]            3           4            3           4
#>  [87,]            4           3            3           3
#>  [88,]            3           1            3           3
#>  [89,]            2           3            2           3
#>  [90,]            2           2            2           3
#>  [91,]            2           2            3           3
#>  [92,]            3           3            3           3
#>  [93,]            2           2            2           3
#>  [94,]            1           1            2           2
#>  [95,]            2           2            3           3
#>  [96,]            2           3            3           3
#>  [97,]            2           3            3           3
#>  [98,]            3           3            3           3
#>  [99,]            1           2            2           2
#> [100,]            2           2            2           3
#> [101,]            3           4            5           5
#> [102,]            2           2            4           4
#> [103,]            5           3            5           5
#> [104,]            3           3            4           4
#> [105,]            4           3            5           5
#> [106,]            5           3            5           5
#> [107,]            1           2            3           4
#> [108,]            5           3            5           4
#> [109,]            4           2            5           4
#> [110,]            5           5            5           5
#> [111,]            4           4            4           5
#> [112,]            4           2            4           4
#> [113,]            4           3            4           5
#> [114,]            2           2            4           5
#> [115,]            2           2            4           5
#> [116,]            4           4            4           5
#> [117,]            4           3            4           4
#> [118,]            5           5            5           5
#> [119,]            5           2            5           5
#> [120,]            3           1            4           3
#> [121,]            4           4            5           5
#> [122,]            2           2            4           5
#> [123,]            5           2            5           5
#> [124,]            3           2            4           4
#> [125,]            4           4            5           5
#> [126,]            5           4            5           4
#> [127,]            3           2            3           4
#> [128,]            3           3            4           4
#> [129,]            4           2            4           5
#> [130,]            5           3            5           4
#> [131,]            5           2            5           4
#> [132,]            5           5            5           5
#> [133,]            4           2            4           5
#> [134,]            3           2            4           3
#> [135,]            3           2            4           3
#> [136,]            5           3            5           5
#> [137,]            3           4            4           5
#> [138,]            4           3            4           4
#> [139,]            3           3            3           4
#> [140,]            4           3            4           5
#> [141,]            4           3            4           5
#> [142,]            4           3            4           5
#> [143,]            2           2            4           4
#> [144,]            4           4            5           5
#> [145,]            4           4            5           5
#> [146,]            4           3            4           5
#> [147,]            3           2            4           4
#> [148,]            4           3            4           5
#> [149,]            3           4            4           5
#> [150,]            3           3            4           4
discretize_vector(iris[,5], n=5, method="natural")
#>   [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
#>  [38] 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
#>  [75] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3
#> [112] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
#> [149] 3 3
```

<sup>Created on 2024-10-10 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Closed** 2024-10-10 09:40 UTC
